erahtur/urls.py
# _*_coding: utf-8 _*_
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from os.path import join
from village.views import *
from django.contrib.auth import views as auth_views
from django.views.generic.simple import direct_to_template
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Example:
    # (r'^erahtur/', include('erahtur.foo.urls')),
    (r'^$', redirect),
    url(r'^login_page/$', login_page, name="login_page"),
    url(r'^organizations/$', org_list, name='org_list'),
    url(r'^publications/tags/(\d+)/$', pubs_by_tag, name='pubs_by_tag'),
    url(r'^publications/news/$', direct_to_template, 
        {'template': 'publications/all_publications_types.html'}, 
        name='all_publications_types'),
    url(r'^publications/news/(\w+)/(\d+)/$', pub_list, name='pub_list'),
    url(r'^organizations/(\d+)/$', organization, name='organization'),
    url(r'^publications/(\d+)/$', publication, name='publication'),
    url(r'^publications/(\d+)/comments/new/$', add_comment, name='add_comment'),
    url(r'^ajax_news_block/$', ajax_news_block, name='ajax_news_block'),
    url(r'^pub_archive/$', publications_archive, name='publications_archive'),
    url(r'^pub_archive_months/(\d{4})/(\d+)/$', pub_archive_months, name='pub_archive_months'),
    url(r'^history/$', hist_list, name='hist_list'),
    url(r'^history/(\d+)/$', history, name='history'),
    url(r'^neighbours/$', neighbour_list, name='neighbour_list'),
    url(r'^neighbours/(\d+)/$', neighbour, name='neighbour'),
    url(r'^creation/$', direct_to_template, {'template': 'creation/creation.html'}, name='creation'),
    url(r'^creation/music/$', music, name='music'),
    url(r'^creation/photoalbums/$', photoalbums_list, name='photoalbums'),
    url(r'^creation/photoalbum/(\d+)/$', photoalbum, name='photoalbum'),
    url(r'^creation/panorams/(\d+)/$', panorama, name='panorama'),
    url(r'^creation/panorams_list/$', panorams_list, name='panorams_list'),
    url(r'^creation/panorams/tags/(\d+)/$', panorams_by_tag, name='panorams_by_tag'),
    url(r'^links/$', links, name='links'),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    #(r'^accounts/', include('registration.urls')),
    #(r'^accounts/', include('registration.backends.default.urls')),
    (r'^accounts/log_in/$', log_in),
    (r'^accounts/logout/$', logout),
    (r'^accounts/login_please', direct_to_template, {'template':'login_error.html'}),
    (r'^accounts/registration/$', registration),
    (r'^accounts/is_username_unique/$', is_username_unique),
    #(r'^accounts/create_user_profile/$', create_user_profile),
    (r'^accounts/user_profile_handle/$', user_profile_handle),
    (r'^accounts/user_profile_creation_error/$', direct_to_template, {'template': 'user_profile_creation_error.html'}),
    #(r'^accounts/user_profile_creation_error/$', direct_to_template, {'template': 'user_profile_creation_error.html'}),
    (r'^accounts/user_profile/(\w+)/$', user_profile),
    (r'^accounts/thanks/$', direct_to_template, {'template':'registration/thanks.html',}),
    url(r'^search/$', search, name='search'),
    (r'^forum/', include('forum.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

erahtur/village/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings as django_settings
from tinymce import models as tinymce_models
from django.contrib.auth.models import User
import tagging
from tagging.fields import TagField
from tagging.models import Tag
from os import path
from django.db.models import signals
from PIL import Image
from pytils.translit import translify
from django.core.files.storage import FileSystemStorage
from django.db.models.fields.files import FileField
from html2text import html2text as h2t
from re import sub

class SongField(FileField):
    def __init__(self, *args, **kwargs):
        super(SongField, self).__init__(*args, **kwargs)
    
    def translit(self, name):
        output_name = []
        for letter in name:
            try:
                out_letter = translify(letter)
            except ValueError:
                out_letter = '1'
            output_name.append(out_letter)
        output_name = ''.join(output_name)
        return output_name
    
    def pre_save(self, model_instance, add):
         "Returns field's value just before saving."
         file = super(FileField, self).pre_save(model_instance, add)
         if file and not file._committed:
             # Commit the file to storage prior to saving the model
             file.name = self.translit(file.name)
             file.save(file.name, file, save=False)
         return file
        

class MyPhotoField(SongField, models.ImageField):
    pass


class SongSystemStorage(FileSystemStorage):
    def __init__(self, option=None):
        #if not option:
        #    option = django_settings.CUSTOM_STORAGE_OPTIONS
        super(SongSystemStorage, self).__init__(option)
    
    def delete(self, name):
        super(SongSystemStorage, self).delete(name)
    
    def exists(self, name):
        super(SongSystemStorage, self).exists(name)
    
    def listdir(self, path):
        super(SongSystemStorage, self).listdir(path)
    
    def size(self, name):
        super(SongSystemStorage, self).size(name)
    
    def url(self, name):
        super(SongSystemStorage, self).url(name)
    
    def translit(self, name):
        output_name = []
        orig_url = self.url(name)
        for letter in name:
            try:
                out_letter = translify(letter)
            except ValueError:
                out_letter = '1'
            output_name.append(out_letter)
        output_name = ''.join(output_name)
        return output_name
    
    def save(self, name, content):
        translit_name = self.translit(name)
        print content.size, content.name, translit_name
        super(SongSystemStorage, self).save(translit_name, content) 
    
song_storage = SongSystemStorage()
        
# Create your models here.
    

class Organization(models.Model):
    name = models.CharField(u'название', max_length=50)
    about = tinymce_models.HTMLField(u'описание')
    sort = models.IntegerField(verbose_name=u'порядок следования', default=0)
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ("sort",)
        verbose_name = u'организация'
        verbose_name_plural = u'Организации'

        
class Publication(models.Model):
    title = models.CharField(u'название', max_length = 50)
    preface = tinymce_models.HTMLField(u'вступление')
    content = tinymce_models.HTMLField(u'содержание')
    location = models.CharField(u'место', max_length = 20, choices = (
        ('district', u'округ'),
        ('region', u'район'),
        ('oblast', u'область'),
    ))
    date = models.DateTimeField(verbose_name = u'дата')
    archive = models.BooleanField(verbose_name=u'в архив?', default=False)
    tags = TagField(verbose_name=u'Тэги')
    
    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('publication', args=[self.id])
    
    def set_tags(self, tags):
        Tag.objects.update(self, tags)
    
    def get_tags(self):
        return Tag.objects.get_for_object(self)
    
    def raw_text(self, html_field): # makes practically raw text from html
        #delete additional signs after h2t function
        return sub('[\t\n\r*#]+', ' ', h2t(html_field))
        
    def raw_publication(self): 
        return self.raw_title() + self.raw_preface() + self.raw_content()
    
    def raw_title(self):
        return self.raw_text(self.title).lower()
    
    def raw_preface(self):
        return self.raw_text(self.preface).lower()

    def raw_content(self):
        return self.raw_text(self.content).lower()
            
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ("-date",)
        verbose_name = u'публикация'
        verbose_name_plural = u'Публикации'
        

def publication_post_save_handler(sender, **kwargs):
    if kwargs.get("created", False):
        ids = []
        for loc in ["district", "region", "oblast"]:
            # all non-archive pubs older than 100 last pubs
            for pub in Publication.objects.filter(location=loc, archive=False)[100:]:
                ids.append(pub.pk)
        if ids:
            # its should be in archive
            Publication.objects.filter(pk__in=ids).update(archive=True) 
signals.post_save.connect(publication_post_save_handler, sender=Publication)


class Comment(models.Model):
    publication = models.ForeignKey(Publication)
    author = models.ForeignKey(User)
    text = models.TextField(verbose_name=u'комментарий')
    date_added = models.DateTimeField(auto_now_add=True)


class History(models.Model):
    period = models.CharField(u'период', max_length = 50)
    content = tinymce_models.HTMLField(u'содержание')
    sort = models.IntegerField(verbose_name=u'порядок следования', default=0)
    
    def __unicode__(self):
        return self.period
    
    class Meta:
        ordering = ('sort',)
        verbose_name = u'исторический период'
        verbose_name_plural = u'Исторические периоды'


class PublicationPhoto(models.Model):
    image = MyPhotoField(u'фото', upload_to='photos/publications')
    description = models.CharField(u'описание', max_length=100)
    pub = models.ForeignKey(Publication)
    
    class Meta:
        verbose_name_plural = u'Фотографии к публикации'
    
    def __unicode__(self):
        return u'фото к публикации'


class HistoryPhoto(models.Model):
    image = MyPhotoField(u'фото', upload_to='photos/history')
    description = models.CharField(u'описание', max_length=100)
    history = models.ForeignKey(History)  

    class Meta:
        verbose_name_plural = u'Фотографии к историческому периоду'
    
    def __unicode__(self):
        return u'фото периода'

    
class Neighbour(models.Model):
    name = models.CharField(u'название', max_length = 50)
    content = tinymce_models.HTMLField(u'содержание')
    sort = models.IntegerField(verbose_name=u'порядок следования' ,default=0)   
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ('sort', )
        verbose_name = u'сосед'
        verbose_name_plural = u'Соседи'


class NeighbourPhoto(models.Model):
    image = MyPhotoField(u'фото', upload_to='photos/neighbours')
    description = models.CharField(u'описание', max_length=100)
    neighbour = models.ForeignKey(Neighbour)

    class Meta:
        verbose_name_plural = u'Фотографии соседа'
    
    def __unicode__(self):
        return u'фото соседа'


class OrganizationPhoto(models.Model):
    image = MyPhotoField(u'фото', upload_to='photos/organizations')
    description = models.CharField(u'описание', max_length=100)
    organization = models.ForeignKey(Organization)    

    class Meta:
        verbose_name_plural = u'Фотографии организации'
    
    def __unicode__(self):
        return u'фото организации'


class Song(models.Model):
    song = SongField(verbose_name=u'трек', upload_to='audio')
    name = models.CharField(u'название', max_length=80, blank=True, null=True)
    artist = models.CharField(u'исполнитель', max_length=80, blank=True, null=True)
    year = models.PositiveIntegerField(verbose_name=u'год', blank=True, null=True)
               
    class Meta:
        ordering = ('-year', )
        verbose_name = u'трек'
        verbose_name_plural = u'Аудиозаписи'
    
    def __unicode__(self):
        return u'трек'


class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    avatar = MyPhotoField(u'аватар', upload_to='photos/user_avatars', blank=True)
    first_name = models.CharField(u'имя', max_length=30, blank=True)
    last_name = models.CharField(u'фамилия', max_length=30, blank=True)
    patronymic = models.CharField(u'отчество', max_length=30, blank=True)
    birth_date = models.DateField(verbose_name=u'дата рождения', blank=True, null=True)
    icq = models.CharField(verbose_name='ICQ', max_length=20, blank=True, null=True)
    location = models.CharField(verbose_name=u'место жительства', max_length=60, blank=True, null=True)
    #site = models.URLField(u'сайт', max_length=80, blank=True, null=True, verify_exists=False)
    phones = models.TextField(u'телефоны', blank=True)
    sites = models.TextField(u'сайты', blank=True)
    #auth_token = models.CharField(u'входной токен', max_length=16 ,blank=True)
    
    class Meta:
        verbose_name = u'профиль пользователя'
        verbose_name_plural = u'Профили пользователей'


class PhotoAlbum(models.Model):
    name = models.CharField(u'название', max_length=50)
    description = models.CharField(u'описание', max_length=150, blank=True)

    class Meta:
        verbose_name = u'фотоальбом'
        verbose_name_plural = u'Фотоальбомы'    


class Photo(models.Model):
    album = models.ForeignKey('PhotoAlbum', related_name='photos')
    image = MyPhotoField(u'фото', upload_to='photos/photos')
    description = models.CharField(u'описание', max_length=100, blank=True)
    key_photo = models.BooleanField(u'обложка')
    
    class Meta:

erahtur/templates/erahtur_main.html
<!DOCTYPE html>
<html>
	
	<head>
		{% block title %}{% endblock %}
		{% load navbar %}

		<link rel="stylesheet" href="{{ MEDIA_URL }}css/mediaboxAdvBlack21.css" type="text/css" media="screen">
		{% comment %}
		<link rel='stylesheet' type='text/css' href='{{ MEDIA_URL }}css/styles.css'></link>
		{% endcomment %}
		<link rel='stylesheet' type='text/css' href='{{ MEDIA_URL }}css/layout.css'></link>
		<link rel='stylesheet' type='text/css' href='{{ MEDIA_URL }}css/navbar.css'></link>
		<link rel='stylesheet' type='text/css' href='{{ MEDIA_URL }}css/tabs.css'></link>
		<link rel='stylesheet' type='text/css' href='{{ MEDIA_URL }}css/publication.css'></link>
		<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/sidebar.css"></link>
		<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/diff_content.css"></link>
		<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/search.css"></link>
		<script type='text/javascript' src='{{ MEDIA_URL }}js/mootools-1.2.4-core-yc.js'></script>
		<script type="text/javascript" src="{{ MEDIA_URL }}js/mediaboxAdv-1.3.4b.js"></script>
		{% block extrahead %}{% endblock %}
		<script type='text/javascript' src='{{ MEDIA_URL }}js/navbar.js'></script>
		{% comment %}
		<script type='text/javascript' src='{{ MEDIA_URL }}js/mooImageLayer.js'></script>
		{% endcomment %}
		<script type='text/javascript' src='{{ MEDIA_URL }}js/mootools-1.2.4.4-more.js'></script>
		<script type='text/javascript' src='{{ MEDIA_URL }}js/registration.js'></script>
	</head>
	
	<body>
	<!-- Yandex.Metrika counter -->
<div style="display:none;"><script type="text/javascript">
(function(w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter12352210 = new Ya.Metrika({id:12352210, enableAll: true});
        }
        catch(e) { }
    });
})(window, "yandex_metrika_callbacks");
</script></div>
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
<noscript><div><img src="//mc.yandex.ru/watch/12352210" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
		
		<div id="wrapper">
			<div id="header">
				<h1>Ерахтур</h1>
			</div>
			<div id='navbar'>
				<ul>
					{% navbar %}
				</ul>
			</div>
			<div id="middle">
				<div id="container">
					<div id="content">
						{% block content %}
						{% endblock %}
					</div>
				</div>
				
				{% block right_column %}
				{% comment %}<div id="sidebar">					

						<div id="accordion">
						{% for year, months in date_pairs_processor.items %}
							<h3 class="toggler">Год {{ year }}</h3>
							<div class="element">
								<ul>
								{% for month in months %}
									<li>
										<a href="{% url pub_archive_months year month %}">{{ month|month_name }}</a>
									</li>
								{% endfor %}
								</ul>
							</div>
						{% endfor %}
						</div>

					<div class="sidebar_wrapper">
						<h3 class="title">Архив новостей</h3>
						<div class="archive">
						{% if date_pairs_processor %}
							{% for year, months in date_pairs_processor.items %}
								<h3 class="archive_year">Год {{ year }}</h3>
								<div>
									<ul>
									{% for month in months %}
										<li>
											<a href="{% url pub_archive_months year month %}">{{ month|month_name }}</a>
										</li>
									{% endfor %}
									</ul>
								</div>
							{% endfor %}
						{% else %}
							<p>Архив пока пуст</p>
						{% endif %}
						</div>
					</div>

					<div class="sidebar_wrapper">
						<div class="tag_cloud">
						{% tag_cloud_for_model village.Publication as tags with min_count=3 distribution=linear steps=10 %}
				    {% for tag in tags %}
							{% ifequal tag.font_size 10 %}
				    		<a class="cloud_tag" href="{% url pubs_by_tag tag.id %}" style="font-size: 2em">
									{{ tag.name|cut:" " }}
								</a>
							{% else %}
								<a class="cloud_tag" href="{% url pubs_by_tag tag.id %}" style="font-size: 1.{{ tag.font_size }}em">
									{{ tag.name|cut:" " }}
								</a>
							{% endifequal %}														
				    {% endfor %}
						</div>
					</div>
				</div>{% endcomment %}
				{% endblock %}
					
			</div>
			<div id="before_footer">
			</div>
		</div>

		<div id="footer" style="position: fixed; bottom: 0;">
			
			<div id="search">
				<form action="{% url search %}">
					<label for="id_search" id="search_text">Поиск:</label>
					<input name="id_search" type="text" />
				</form>
			</div>
			
			{% if user.is_authenticated %}			
				<div class="username">
					<a href='/accounts/user_profile/{{ user.username }}'>
						{{ user.username }}
					</a> 
					{% if user.is_superuser %} <span>(superuser)</span> {% endif %}
				</div>
				<form id="hidden_chat_form" method="POST" action="{% chat_host_name %}" target="_blank">
					<input type="text" name="nickname" value="{{ user.username }}" />
					<input type="text" name="chat_auth_token" value="{% chat_auth_token user %}" />
					<input type="submit">
				</form>
				<div class="logout_form">
					<form action="/accounts/logout">
						<input type="submit" value="Выход">
					</form>
				</div>
			{% else %}
		  	<div class="login_form">
			    {% if login_error %}
						<form action="/accounts/log_in/" method="POST">
				  		<p>              
								<input class="login" type="text" name="username" value="login" 
								size="12" style="background: #A60000; border: none;">
			  	  		<input class="password" type="password" name="password" value="password" 
								size="12" style="background: #A60000; border: none">
			  	  	</p>  
				  	  <input class="login_button" type="submit" value="Вход">
						</form>
					{% else %}
						<form action="/accounts/log_in/" method="POST">
				  		<p>              
								<input class="login" type="text" name="username" value="login" size="12">
			  	  		<input class="password" type="password" name="password" value="password" size="12">
			  	  	</p>  
				  	  <input class="login_button" type="submit" value="Вход">
						</form>
					{% endif %}
					<span class="registration">
						<a href="/accounts/registration/">Регистрация</a>
					</span>
				</div>
			{% endif %}	
		</div>
	<div id="chat_notification_block" class="rc12"></div>
	</body>
</html>

erahtur/templates/hist_list.html
{% extends 'erahtur_main.html' %}
{% block title %}
<title>Ерахтур - история</title>
{% endblock %}
{% block content %}
<div class='content_wrapper'>
	<div id="center_list">
		<h3>История</h3>
		<ul id='hist_list'>
		{% for hist in hist_list %}
			<li><a href='{% url history hist.id %}'>{{ hist.period }}</a></li>
		{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}

erahtur/templates/history.html
{% extends 'erahtur_main.html' %}
{% load navbar %}
{% block title %}
<title>Ерахтур - история</title>
{% endblock %}

{% block content %}

<div class="publication_wrapper">
	<div class="publication no_border">
		<h3>История / <span class="active_font">{{ history.period }}</span></h3>
		<div class="entry"> {{ history.content|safe }} </div>
	</div>

		{% if photos %}
		<hr>
		<div id="photos_block_title">
			Фотоблок (<span class="active_font">{{ photos|length }}</span>)
		</div>		
		<div id="photos_block">
			{% for photo in photos %}
			<a href="{{ photo.image.url }}" rel="lightbox[set1]" title="{{ photo.description }}">
				<img src="{{ photo|get_thumbnail }}" alt="{{ photo.description }}" class="photo_thumb rc12"/>
			</a>
			{% endfor %}
		</div>
		{% endif %}

</div>
	
{% endblock %}

erahtur/templates/links.html
{% extends 'erahtur_main.html' %}
{% block title %}
<title>Ерахтур - ссылки</title>
{% endblock %}

{% block extrahead %}
<script type='text/javascript' src='{{ MEDIA_URL }}js/links_accordion.js'></script>
{% endblock %}

{% block content %}

<div class="content_wrapper">
	<div id="accordion">
	{% for link_section in links_sections %}	
		<h3 class="toggler">{{ link_section.name }}</h3>
		<div class="element">
			<ul>
				{% for link in link_section.links.all %}
				<li><a href='{{ link.href }}'>{{ link.name }}</a></li>
				{% endfor %}
			</ul>
		</div>
	{% endfor %}

	</div>
</div>

{% endblock %}

erahtur/templates/login_error.html
{% extends 'work.html' %}

{% block content %}
  <h4>
    You should be logged in to have access to this part
  </h4>
  <h4>
    Log in, please
  </h4>
{% endblock %}

erahtur/templates/login_page.html
{% extends "erahtur_main.html" %}

{% block content %}
<div class="content_wrapper">
	<div id="login_page">
		
		<h2>Вход на сайт</h2>
		
		<div class="login_form">
		  {% if login_errors %}
			<form action="{% url login_page %}?where={{ where }}" method="POST" class="login_page_form">
		 		<p>              
					<input class="login" type="text" name="username" value="login" 
					size="12" style="background: #A60000; border: none;">
			  	<input class="password" type="password" name="password" value="password" 
					size="12" style="background: #A60000; border: none">
			  	</p>  
		 	  <input class="login_button" type="submit" value="Вход">
			</form>
		{% else %}
			<form action="{% url login_page %}?where={{ where }}" method="POST" class="login_page_form">
		 		<p>              
					<input class="login" type="text" name="username" value="login" size="12">
			  	<input class="password" type="password" name="password" value="password" size="12">
			  	</p>  
		 	  <input class="login_button" type="submit" value="Вход">
			</form>
		{% endif %}
		</div>
	</div>
</div>
{% endblock %}

erahtur/templates/neighbour.html
{% extends 'erahtur_main.html' %}
{% load navbar %}
{% block title %}
<title>Ерахтур - соседи</title>
{% endblock %}

{% block content %}

<div class="publication_wrapper">
	<div class="publication no_border">
		<h3>Соседи / <span class="active_font">{{ neighbour.name }}</span></h3>
		<div class="entry"> {{ neighbour.content|safe }} </div>
	</div>
		{% if photos %}
		<hr>
		<div id="photos_block_title">
			Фотоблок (<span class="active_font">{{ photos|length }}</span>)
		</div>		
		<div id="photos_block">
			{% for photo in photos %}
			<a href="{{ photo.image.url }}" rel="lightbox[set1]" title="{{ photo.description }}">
				<img src="{{ photo|get_thumbnail }}" alt="{{ photo.description }}" class="photo_thumb rc12"/>
			</a>
			{% endfor %}
		</div>
		{% endif %}
</div>

{% endblock %}

erahtur/templates/user_profile_handle.html
{% extends 'erahtur_main.html' %}
{% load navbar %}
{% block title %}
<title>Ерахтур - {{ user.username }}</title>
{% endblock %}

{% block content %}
<div class="user_content_wrapper">

	<form method='POST' enctype="multipart/form-data" action='.' id="profile_form">
	<h3 class="user_profile_name">Профиль пользователя {{ user.username }}</h3>	
	{% with user.get_profile as profile %}
		<div class="avatar_image">
		{% if profile.avatar %}
			<img src="{{ profile.avatar|get_thumbnail }}" id="avatar_image">
			<br>
			<a href='#' id="change_avatar">Изменить аватар</a>
		{% endif %}
		</div>
		

		<table id="profile_form_table" cellspacing="5px">

			{% if profile.avatar %}
			<tr class="new_avatar">
				<td class="label">
					<label id="for_id_avatar_new">Новый аватар:</label>
				</td>
				<td>
					<input type="file" id="id_avatar_new" name="avatar" />
				</td>
			</tr>		
			
			{% else %}
			<tr>
				<td class="label">	
					{{ form.avatar.errors }}
					<label for="id_avatar">Аватар:</label>
				</td>		
				<td class="value">
				{{ form.avatar }}
				</td>
			</tr>
			{% endif %}	

			<tr>
				<td class="label">
					{{ form.last_name.errors }}
					<label for="id_last_name">Фамилия:</label>
				</td>
				<td class="value">
					<span>{{ form.last_name }}</span>
				</td>
			</tr>
	
			<tr>
				<td class="label">
					{{ form.first_name.errors }}
					<label for="id_first_name">Имя:</label>
				</td>
				<td class="value">
					<span>{{ form.first_name }}</span>
				</td>
			</tr>
	
			<tr>
				<td class="label">
					{{ form.patronymic.errors }}
					<label for="id_patronymic">Отчество:</label>
				</td>
				<td class="value">
					<span>{{ form.patronymic }}</span>
				</td>
			</tr>
	
			<tr>	
				<td class="label">
					{{ form.icq.errors }}
					<label for="id_icq">ICQ:</label>
				</td>
				<td class="value">	
					{{ form.icq }}
				</td>
			</tr>
	
			<tr>
				<td class="label phone_cell">
					{{ form.phone.errors }}
					<label for="id_phone">Телефон:</label>
				</td>
				<td class="value">
					{% for phone in phones_list %}
						<p><input class="phone" type="text" name="phone" maxlength="20" value="{{ phone }}"></p>
					{% empty %}
						<p><input class="phone" type="text" name="phone" maxlength="20"></p>
					{% endfor %}
					<a class="add_phone no_decor active_font" href="#">+</a>
				</td>
			</tr>
	
			<tr>
				<td class="label">
					{{ form.location.errors }}
					<label for="id_location">Место жительства:</label>
				</td>
				<td class="value">
					{{ form.location }}
				</td>
			</tr>
	
			<tr>
				<td class="label">
				<div class="field_wrapper">Дата рождения:</div>
				</td>
				<td class="value">
				<div class="field_wrapper">
					{{ form.year.errors }}
					{{ form.month.errors }}
					{{ form.day.errors }}
					<span>{{ form.year }} 	{{ form.month }} 	{{ form.day }}</span>
				</div>
				</td>
			</tr>
	
			<tr>
				<td class="label site_cell">
					{{ form.sites.errors }}
					<label for="id_site">Сайт:</label>
				</td>
				<td class="value">
					{% for site in sites_list %}
						<p><input class="site" type="text" name="site" maxlength="60" value="{{ site }}"></p>
					{% empty %}
						<p><input class="site" type="text" name="site" maxlength="60"></p>
					{% endfor %}
					<a class="add_site no_decor active_font" href="#">+</a>
					
				</td>
			</tr>
		</table>
		<input type='submit' value='Сохранить профиль' class="profile_form_submit" />
	{% endwith %}
	</form>
</div>

{% endblock %}