erahtur/urls.py
# _*_coding: utf-8 _*_
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from os.path import join
from village.views import *
from django.contrib.auth import views as auth_views
from django.views.generic.simple import direct_to_template
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Example:
    # (r'^erahtur/', include('erahtur.foo.urls')),
    (r'^$', redirect),
    url(r'^login_page/$', login_page, name="login_page"),
    url(r'^organizations/$', org_list, name='org_list'),
    url(r'^publications/tags/(\d+)/$', pubs_by_tag, name='pubs_by_tag'),
    url(r'^publications/news/$', direct_to_template, 
        {'template': 'publications/all_publications_types.html'}, 
        name='all_publications_types'),
    url(r'^publications/news/(\w+)/(\d+)/$', pub_list, name='pub_list'),
    url(r'^organizations/(\d+)/$', organization, name='organization'),
    url(r'^publications/(\d+)/$', publication, name='publication'),
    url(r'^publications/(\d+)/comments/new/$', add_comment, name='add_comment'),
    url(r'^ajax_news_block/$', ajax_news_block, name='ajax_news_block'),
    url(r'^pub_archive/$', publications_archive, name='publications_archive'),
    url(r'^pub_archive_months/(\d{4})/(\d+)/$', pub_archive_months, name='pub_archive_months'),
    url(r'^history/$', hist_list, name='hist_list'),
    url(r'^history/(\d+)/$', history, name='history'),
    url(r'^neighbours/$', neighbour_list, name='neighbour_list'),
    url(r'^neighbours/(\d+)/$', neighbour, name='neighbour'),
    url(r'^creation/$', direct_to_template, {'template': 'creation/creation.html'}, name='creation'),
    url(r'^creation/music/$', music, name='music'),
    url(r'^creation/photoalbums/$', photoalbums_list, name='photoalbums'),
    url(r'^creation/photoalbum/(\d+)/$', photoalbum, name='photoalbum'),
    url(r'^creation/panorams/(\d+)/$', panorama, name='panorama'),
    url(r'^creation/panorams_list/$', panorams_list, name='panorams_list'),
    url(r'^creation/panorams/tags/(\d+)/$', panorams_by_tag, name='panorams_by_tag'),
    url(r'^links/$', links, name='links'),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    #(r'^accounts/', include('registration.urls')),
    #(r'^accounts/', include('registration.backends.default.urls')),
    (r'^accounts/log_in/$', log_in),
    (r'^accounts/logout/$', logout),
    (r'^accounts/login_please', direct_to_template, {'template':'login_error.html'}),
    (r'^accounts/registration/$', registration),
    (r'^accounts/is_username_unique/$', is_username_unique),
    #(r'^accounts/create_user_profile/$', create_user_profile),
    (r'^accounts/user_profile_handle/$', user_profile_handle),
    (r'^accounts/user_profile_creation_error/$', direct_to_template, {'template': 'user_profile_creation_error.html'}),
    #(r'^accounts/user_profile_creation_error/$', direct_to_template, {'template': 'user_profile_creation_error.html'}),
    (r'^accounts/user_profile/(\w+)/$', user_profile),
    (r'^accounts/thanks/$', direct_to_template, {'template':'registration/thanks.html',}),
    url(r'^search/$', search, name='search'),
    (r'^forum/', include('forum.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

erahtur/village/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings as django_settings
from tinymce import models as tinymce_models
from django.contrib.auth.models import User
import tagging
from tagging.fields import TagField
from tagging.models import Tag
from os import path
from django.db.models import signals
from PIL import Image
from pytils.translit import translify
from django.core.files.storage import FileSystemStorage
from django.db.models.fields.files import FileField
from html2text import html2text as h2t
from re import sub

class SongField(FileField):
    def __init__(self, *args, **kwargs):
        super(SongField, self).__init__(*args, **kwargs)
    
    def translit(self, name):
        output_name = []
        for letter in name:
            try:
                out_letter = translify(letter)
            except ValueError:
                out_letter = '1'
            output_name.append(out_letter)
        output_name = ''.join(output_name)
        return output_name
    
    def pre_save(self, model_instance, add):
         "Returns field's value just before saving."
         file = super(FileField, self).pre_save(model_instance, add)
         if file and not file._committed:
             # Commit the file to storage prior to saving the model
             file.name = self.translit(file.name)
             file.save(file.name, file, save=False)
         return file
        

class MyPhotoField(SongField, models.ImageField):
    pass


class SongSystemStorage(FileSystemStorage):
    def __init__(self, option=None):
        #if not option:
        #    option = django_settings.CUSTOM_STORAGE_OPTIONS
        super(SongSystemStorage, self).__init__(option)
    
    def delete(self, name):
        super(SongSystemStorage, self).delete(name)
    
    def exists(self, name):
        super(SongSystemStorage, self).exists(name)
    
    def listdir(self, path):
        super(SongSystemStorage, self).listdir(path)
    
    def size(self, name):
        super(SongSystemStorage, self).size(name)
    
    def url(self, name):
        super(SongSystemStorage, self).url(name)
    
    def translit(self, name):
        output_name = []
        orig_url = self.url(name)
        for letter in name:
            try:
                out_letter = translify(letter)
            except ValueError:
                out_letter = '1'
            output_name.append(out_letter)
        output_name = ''.join(output_name)
        return output_name
    
    def save(self, name, content):
        translit_name = self.translit(name)
        print content.size, content.name, translit_name
        super(SongSystemStorage, self).save(translit_name, content) 
    
song_storage = SongSystemStorage()
        
# Create your models here.
    

class Organization(models.Model):
    name = models.CharField(u'название', max_length=50)
    about = tinymce_models.HTMLField(u'описание')
    sort = models.IntegerField(verbose_name=u'порядок следования', default=0)
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ("sort",)
        verbose_name = u'организация'
        verbose_name_plural = u'Организации'

        
class Publication(models.Model):
    title = models.CharField(u'название', max_length = 50)
    preface = tinymce_models.HTMLField(u'вступление')
    content = tinymce_models.HTMLField(u'содержание')
    location = models.CharField(u'место', max_length = 20, choices = (
        ('district', u'округ'),
        ('region', u'район'),
        ('oblast', u'область'),
    ))
    date = models.DateTimeField(verbose_name = u'дата')
    archive = models.BooleanField(verbose_name=u'в архив?', default=False)
    tags = TagField(verbose_name=u'Тэги')
    
    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('publication', args=[self.id])
    
    def set_tags(self, tags):
        Tag.objects.update(self, tags)
    
    def get_tags(self):
        return Tag.objects.get_for_object(self)
    
    def raw_text(self, html_field): # makes practically raw text from html
        #delete additional signs after h2t function
        return sub('[\t\n\r*#]+', ' ', h2t(html_field))
        
    def raw_publication(self): 
        return self.raw_title() + self.raw_preface() + self.raw_content()
    
    def raw_title(self):
        return self.raw_text(self.title).lower()
    
    def raw_preface(self):
        return self.raw_text(self.preface).lower()

    def raw_content(self):
        return self.raw_text(self.content).lower()
            
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ("-date",)
        verbose_name = u'публикация'
        verbose_name_plural = u'Публикации'
        

def publication_post_save_handler(sender, **kwargs):
    if kwargs.get("created", False):
        ids = []
        for loc in ["district", "region", "oblast"]:
            # all non-archive pubs older than 100 last pubs
            for pub in Publication.objects.filter(location=loc, archive=False)[100:]:
                ids.append(pub.pk)
        if ids:
            # its should be in archive
            Publication.objects.filter(pk__in=ids).update(archive=True) 
signals.post_save.connect(publication_post_save_handler, sender=Publication)


class Comment(models.Model):
    publication = models.ForeignKey(Publication)
    author = models.ForeignKey(User)
    text = models.TextField(verbose_name=u'комментарий')
    date_added = models.DateTimeField(auto_now_add=True)


class History(models.Model):
    period = models.CharField(u'период', max_length = 50)
    content = tinymce_models.HTMLField(u'содержание')
    sort = models.IntegerField(verbose_name=u'порядок следования', default=0)
    
    def __unicode__(self):
        return self.period
    
    class Meta:
        ordering = ('sort',)
        verbose_name = u'исторический период'
        verbose_name_plural = u'Исторические периоды'


class PublicationPhoto(models.Model):
    image = MyPhotoField(u'фото', upload_to='photos/publications')
    description = models.CharField(u'описание', max_length=100)
    pub = models.ForeignKey(Publication)
    
    class Meta:
        verbose_name_plural = u'Фотографии к публикации'
    
    def __unicode__(self):
        return u'фото к публикации'


class HistoryPhoto(models.Model):
    image = MyPhotoField(u'фото', upload_to='photos/history')
    description = models.CharField(u'описание', max_length=100)
    history = models.ForeignKey(History)  

    class Meta:
        verbose_name_plural = u'Фотографии к историческому периоду'
    
    def __unicode__(self):
        return u'фото периода'

    
class Neighbour(models.Model):
    name = models.CharField(u'название', max_length = 50)
    content = tinymce_models.HTMLField(u'содержание')
    sort = models.IntegerField(verbose_name=u'порядок следования' ,default=0)   
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ('sort', )
        verbose_name = u'сосед'
        verbose_name_plural = u'Соседи'


class NeighbourPhoto(models.Model):
    image = MyPhotoField(u'фото', upload_to='photos/neighbours')
    description = models.CharField(u'описание', max_length=100)
    neighbour = models.ForeignKey(Neighbour)

    class Meta:
        verbose_name_plural = u'Фотографии соседа'
    
    def __unicode__(self):
        return u'фото соседа'


class OrganizationPhoto(models.Model):
    image = MyPhotoField(u'фото', upload_to='photos/organizations')
    description = models.CharField(u'описание', max_length=100)
    organization = models.ForeignKey(Organization)    

    class Meta:
        verbose_name_plural = u'Фотографии организации'
    
    def __unicode__(self):
        return u'фото организации'


class Song(models.Model):
    song = SongField(verbose_name=u'трек', upload_to='audio')
    name = models.CharField(u'название', max_length=80, blank=True, null=True)
    artist = models.CharField(u'исполнитель', max_length=80, blank=True, null=True)
    year = models.PositiveIntegerField(verbose_name=u'год', blank=True, null=True)
               
    class Meta:
        ordering = ('-year', )
        verbose_name = u'трек'
        verbose_name_plural = u'Аудиозаписи'
    
    def __unicode__(self):
        return u'трек'


class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    avatar = MyPhotoField(u'аватар', upload_to='photos/user_avatars', blank=True)
    first_name = models.CharField(u'имя', max_length=30, blank=True)
    last_name = models.CharField(u'фамилия', max_length=30, blank=True)
    patronymic = models.CharField(u'отчество', max_length=30, blank=True)
    birth_date = models.DateField(verbose_name=u'дата рождения', blank=True, null=True)
    icq = models.CharField(verbose_name='ICQ', max_length=20, blank=True, null=True)
    location = models.CharField(verbose_name=u'место жительства', max_length=60, blank=True, null=True)
    #site = models.URLField(u'сайт', max_length=80, blank=True, null=True, verify_exists=False)
    phones = models.TextField(u'телефоны', blank=True)
    sites = models.TextField(u'сайты', blank=True)
    #auth_token = models.CharField(u'входной токен', max_length=16 ,blank=True)
    
    class Meta:
        verbose_name = u'профиль пользователя'
        verbose_name_plural = u'Профили пользователей'


class PhotoAlbum(models.Model):
    name = models.CharField(u'название', max_length=50)
    description = models.CharField(u'описание', max_length=150, blank=True)

    class Meta:
        verbose_name = u'фотоальбом'
        verbose_name_plural = u'Фотоальбомы'    


class Photo(models.Model):
    album = models.ForeignKey('PhotoAlbum', related_name='photos')
    image = MyPhotoField(u'фото', upload_to='photos/photos')
    description = models.CharField(u'описание', max_length=100, blank=True)
    key_photo = models.BooleanField(u'обложка')
    
    class Meta:

erahtur/templates/publications/ajax_news_block.html
{{ news_block|safe }}

erahtur/templates/publications/all_publications_types.html
{% extends 'erahtur_main.html' %}

{% load navbar %}
{% block title %}
<title>Ерахтур - новости</title>
{% endblock %}

{% block content %}
<div class='content_wrapper'>
	<div id="center_list">
		<h3>Новости</h3>
		<ul>
			<li><a href="{% url pub_list 'district' 1 %}">Округ</a></li>
			<li><a href="{% url pub_list 'region' 1 %}">Район</a></li>
			<li><a href="{% url pub_list 'oblast' 1 %}">Область</a></li>
			<li><a href="/pub_archive/">Архив</a></li>
		</ul>
	</div>
</div>

{% endblock %}

{% block right_column %}
	{% right_column %}
{% endblock %}

erahtur/templates/publications/new_pub_list.html
{% extends 'erahtur_main.html' %}
{% load navbar %}
{% load tagging_tags %}
{% block title %}
	<title>Ерахтур - новости</title>
{% endblock %}
{% block content %}
	<div class="content_wrapper">

		<div id="tabBox">
			<div class="tabsHolder">
				<ul class="tabSet" style="display: block;">
					<li class="off">
						<a href="/publications/news/district/1/" class="no_decor" id="pub_district">Округ</a>
					</li>
					<li class="off">
						<a href="/publications/news/region/1/" class="no_decor" id="pub_region">Район</a>
					</li>
					<li class="off">
						<a href="/publications/news/oblast/1/" class="no_decor" id="pub_oblast">Область</a>
					</li>
				</ul>		  
			</div>
		</div>

		{% comment %}<h3>Новости / <span class="active_font">{{ russian_pub_type }}</span></h3>{% endcomment %}
		{% if pub_list %}
			{% for tuple in pub_list %}
				<div class="publication">
					<p class="title">							
						<a href="{% url publication tuple.0.id %}">{{ tuple.0.title }}</a>
					</p>
					<div class="entry"> {{ tuple.0.preface|safe }} </div>
					{% comment %}
					<p class="date">{{ tuple.0.date|pytils_date }}, {{ tuple.0.date|date:"H:i" }}</p>
					{% endcomment %}
					<a style="text-decoration: none;" href='#' class="read" id="read-{{ tuple.0.id }}">&rarr;</a>
					<div class="pub_statistics rc4">
						<div class="pub_date">
							<span>{{ tuple.0.date|pytils_date }}, {{ tuple.0.date|date:"H:i" }}</span>
						</div>
						<div class="pub_words">
							<span>слов:  <span class="active_font">{{ tuple.1.0 }}</span></span>
						</div>
						<div class="pub_photos">
							<span>фото: <span class="active_font">{{ tuple.1.1 }}</span></span>
						</div>
						<div class="pub_comments">
							<span>комментариев: <span class="active_font">{{ tuple.1.2 }}</span></span>
						</div>
					</div>
					<br class="clear">
					{% if tuple.0.get_tags %}
					<div class="pub_tags">
						{% for tag in tuple.0.get_tags %}
								<div class="pub_tag"><a href="{% url pubs_by_tag tag.id %}">{{ tag.name|cut:" " }}</a></div>
						{% endfor %}
					</div>
					<br class="clear">
					{% endif %}
					<p class="spacer"></p>
				</div>
			{% endfor %}			
		{% else %}
			<h3>Тут пока ничего нет. Попробуйте посмотреть на более ранних страницах</h3>
		{% endif %}		
	
		<div>
			<p>
	       {% for i in pages %}
					{% ifequal i current_page %}
						<span class="filmfeed_pages_disabled">{{ i }}</span>
					{% else %}		
	       		<a class="filmfeed_pages" href="{% url pub_list pub_type i %}">{{ i }}</a>
					{% endifequal %}
				{% endfor %}
		  </p>
		</div>	
	
	</div>
	
	
	
	{% comment %}
	<div class="page_switch">
		<p id="switch_panel">
    	{% for i in pages %}
				{% ifequal i current_page %}
					<span class="filmfeed_pages_disabled" id="switch_panel_{{ i }}">{{ i }}</span>
				{% else %}
					<a href="{% url pub_list pub_type i %}" class="filmfeed_pages" id="switch_panel_{{ i }}">{{ i }}</a>
				{% endifequal %}
			{% endfor %}
  	</p>
		
		<p id="blocks_panel">
      {% for i in pages %}
				{% ifequal i current_page %}
					<span class="filmfeed_blocks_disabled" id="blocks_panel_{{ i }}">1</span>
				{% else %}
					<span class="filmfeed_blocks" id="blocks_panel_{{ i }}">1</span>
				{% endifequal %}
			{% endfor %}
	  </p>
		
	</div>	
	{% endcomment %}
	
	
					
{% endblock %}

{% block right_column %}
	{% right_column %}
{% endblock %}

erahtur/templates/publications/publication.html
{% extends 'erahtur_main.html' %}
{% load navbar %}
{% block title %}
<title>{{ publication.title }}</title>
{% endblock %}
{% block extrahead %}
<script type='text/javascript' src='{{ MEDIA_URL }}js/publication.js'></script>
<script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
<script type="text/javascript">
	new Ya.share({
        element: 'ya_share',
            elementStyle: {
                'type': 'none',
                'border': true,
                'quickServices': ['twitter', '|', 'vkontakte', 'facebook','lj','|','odnoklassniki','moimir']
            },
						description: 'Официальный сайт Ерахтура epaxtyp.com',
            serviceSpecific: {
                twitter: {
                	title: '#epaxtyp / ' + document.title
               },
								vkontakte: {
									title: document.title + ' ' + window.location.href,
									link: window.location.href,
									//title: 'Официальный сайт Ерахтура',
								},
								lj: {
									title: 'Epaxtyp - ' + document.title,
								},
        }
});
</script>
{% endblock %}

{% block content %}
	<div class="publication_wrapper">
		<div class="publication no_border">
			<p class="title"> 
				<a href="{% url publication publication.id %}">{{ publication.title }}</a>
			</p>
			<div class="entry"> {{ publication.content|safe }} </div>
			<div class="pub_statistics rc4">
				<div class="pub_date">
					<span>{{ publication.date|pytils_date }}, {{ publication.date|date:"H:i" }}</span>
				</div>
				<div class="pub_words">
					<span>слов:  <span class="active_font">{{ pub_stats.0 }}</span></span>
				</div>
				<div class="pub_photos">
					<span>фото: <span class="active_font">{{ pub_stats.1 }}</span></span>
				</div>
				<div class="pub_comments">
					<span>комментариев: <span class="active_font">{{ pub_stats.2 }}</span></span>
				</div>
			</div>
			<br class="clear">
			{% if publication.get_tags %}
			<div class="pub_tags">
			{% for tag in publication.get_tags %}
				<div class="pub_tag"><a href="{% url pubs_by_tag tag.id %}">{{ tag.name|cut:"," }}</a></div>
			{% endfor %}
			<br class="clear">
			</div>
			{% endif %}
			<div id="ya_share" class="ya_share"></div>

			{% comment %}
			<p class="date"> {{ publication.date|pytils_date }}, {{ publication.date|date:"H:i" }} </p>
			{% endcomment %}
		</div>

		{% if photos %}
		<hr>
		<div id="photos_block_title">
			Фотоблок (<span class="active_font">{{ photos|length }}</span>)
		</div>		
			<div id="photos_block">
				{% for photo in photos %}
				<a href="{{ photo.image.url }}" rel="lightbox[set1]" title="{{ photo.description }}">
					<img src="{{ photo|get_thumbnail }}" alt="{{ photo.description }}" class="photo_thumb rc12"/>
				</a>
				{% endfor %}
			</div>
		{% endif %}
		
		<hr>
		<div id="comments">
			{% if publication.comment_set.all %}
			<div id="comm_block_title">
				Комментарии (<span class="active_font">{{ pub_stats.2 }}</span>)
			</div>
			{% endif %}
			<div id="comments_block">
				<div id="pub_comments">
					{% if publication.comment_set.all %}
					{% for comment in publication.comment_set.all %}
						<div class="user_comment">
							<div class="comments_avatar rc4">
								<a href="/accounts/user_profile/{{ comment.author.username }}">
									{% if comment.author.userprofile_set.all.0.avatar %}
										<img  class="rc4" alt="{{ comment.author.name }}" width="50" height="50"
										src="{{ comment.author.userprofile_set.all.0.avatar|get_thumbnail }}" >
									{% else %}
										<img alt="{{ comment.author.username }}" src="" >
									{% endif %}
								</a>
							</div>
							<div class="comments_name">
								<a href="/accounts/user_profile/{{ comment.author.username }}">{{ comment.author.username }}</a>
								<span>написал {{ comment.date_added|pytils_date }} в {{ comment.date_added|date:"H:i" }}</span>
							</div>
							<div class="comments_text_block">
								<div class="comments_text rc4">
									<span>{{ comment.text }}</span>
								</div>
							</div>
							<br class="clear">
						</div>
					{% endfor %}
					{% endif %}
					
					{% if user.is_authenticated %}
					<form id="new_comment" method="POST" action="comments/new/">
						<div id="new_comm_block_title">
							Оставить комментарий
						</div>
						<div id="add_comment">
							<div class="comments_avatar">
								<a href="/accounts/user_profile/{{ user.username }}">
									{% if user.userprofile_set.all.0.avatar %}
										<img class="rc4" alt="{{ user.username }}" width="50" height="50"
										src="{{ user.userprofile_set.all.0.avatar|get_thumbnail }}">
									{% else %}
										<img alt="{{ user.username }}" src="">
									{% endif %}
								</a>
							</div>
							<div class="add_comment_text">
								<textarea id="comment_body" name="comments_text" cols="20" rows="4"></textarea>
							</div>
							<div id="comment_button">
								<input type="submit" value="Комментировать" name="commit" id="add_comment_button" disabled="disabled" class="button">
							</div>
						</div>
					</form>
					{% else %}
						<h2 style="font-size: 20px; margin: 30px 0 0">
							Пожалуйста, 
							<a href="{% url login_page%}?where={{ publication.get_absolute_url }}">войдите</a>, 
							чтобы оставить комментарий.
						</h2>
						<h2 style="font-size: 20px; margin: 30px 0 0"> 
							Еще не зарегистрировались? Тогда <a href="/accounts/registration/">вперед</a>.
						</h2>
					{% endif %}	
				</div>
			</div>
		</div>
	</div>


{% endblock %}

{% block right_column %}
	{% right_column %}
{% endblock %}

erahtur/templates/publications/pubs_by_tag.html
{% extends "erahtur_main.html" %}
{% load navbar %}
{% block title %}
<title>Ерахтур - {{ tag.name }}</title>
{% endblock %}
{% block content %}

<div class="content_wrapper">
	
			{% if pub_list %}
			<h2 style="text-align: center;"><span class="active_font">{{ tag.name }}</span></h2>
			{% for tuple in pub_list %}				
				<div class="publication">
					<p class="title">							
						<a href="{% url publication tuple.0.id %}">{{ tuple.0.title }}</a>
					</p>
					<div class="entry"> {{ tuple.0.preface|safe }} </div>
					{% comment %}
					<p class="date">{{ tuple.0.date|pytils_date }}, {{ tuple.0.date|date:"H:i" }}</p>
					{% endcomment %}
					<a style="text-decoration: none;" href='#' class="read" id="read-{{ tuple.0.id }}">&rarr;</a>
					{% comment %}
					<span>(слов: {{ tuple.1.0 }}, фото: {{ tuple.1.1 }})</span>
					{% endcomment %}
					<div class="pub_statistics rc4">
						<div class="pub_date">
							<span>{{ tuple.0.date|pytils_date }}, {{ tuple.0.date|date:"H:i" }}</span>
						</div>
						<div class="pub_words">
							<span>слов:  <span class="active_font">{{ tuple.1.0 }}</span></span>
						</div>
						<div class="pub_photos">
							<span>фото: <span class="active_font">{{ tuple.1.1 }}</span></span>
						</div>
						<div class="pub_comments">
							<span>комментариев: <span class="active_font">{{ tuple.1.2 }}</span></span>
						</div>
					</div>
					<br class="clear">
					<div class="pub_tags">
						{% for tag in tuple.0.get_tags %}
							<div class="pub_tag"><a href="{% url pubs_by_tag tag.id %}">{{ tag.name|cut:" " }}</a></div>
						{% endfor %}
					</div>
					<br class="clear">
					<p class="spacer"></p>
				</div>
			{% endfor %}			
		{% else %}
			<h3>Тут пока ничего нет. Попробуйте посмотреть на более ранних страницах</h3>
		{% endif %}		
	</div>
{% endblock %}

{% block right_column %}
	{% right_column %}
{% endblock %}